### ISSUE TITLE
big beta 'feedback' thread

### ISSUE THREAD

**Issue by owocki** [gitcoinco/ios#10]
post below

**Comment by owocki** [comment]
from email: 

👋 - as someone looking to complete bounties (ie. not post bounties) I don't want to give gitcoin access to write to my public repos. and especially don't want to give read/write access to my private repos. unrelated- there's some clipping here (photo).  The bounty card UI could use some polishing - red/green overlay isn't matching up with the card. at least on iphone x. overall app is clean though 

Inline image 1

**Comment by owocki** [comment]
Dropping a bit of disorganized feedback here for you.

1. Very clean and responsive. I appreciate the simplicity as well.
1. When I click on a given issue "card" I expect to be able to scroll down or see a different view to see the full description. Personally, I don't like that it pops me out of the app to a tab in safari to view that level of detail. I'd prefer to stay in the app for that and have the option of jumping to the issue in Github via a button in the app.
1. It isn't clear upon initially firing up the app what happens to an issue card after I swipe left or right. Will I be able to access in the future? What if I'm unsure at that moment in time whether I like it or not?
* The intersection of 2 and 3 are interesting. The card swiping experience is great, but feels like it pushes a sense of urgency on me when evaluating a given issue. So when I get popped out of the app to read the details of the issue in Github, it sort of contradicts the feeling of urgency I get from the card swiping experience.
1. Given the swiping experience, I was expecting a place in the app where I can review which issues I swiped right on.

Given all of my questions above, I guess I'd ask you what problem you're trying to solve with the app.

**Comment by john-brunelle** [comment]
@owocki this still relevant?
