### ISSUE TITLE
ios app feedback for john

### ISSUE THREAD

**Issue by owocki** [gitcoinco/ios#20]
see comments below

**Comment by owocki** [comment]
http://bits.owocki.com/2K3E3M1r3c3u/Screen%20Shot%202018-04-16%20at%201.29.18%20PM.png

robot only goes halfway down background

**Comment by owocki** [comment]
can't tap on any of the bounties claimed here => http://bits.owocki.com/1A0I0A1E2n2k/Screen%20Shot%202018-04-16%20at%201.30.53%20PM.png

**Comment by john-brunelle** [comment]
> robot only goes halfway down background

fixed

> can't tap on any of the bounties claimed

fixed
