### ISSUE TITLE
Add how to use the app screen

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/ios#25]
Add clear simple language on how to use the app:
*Change X to Next, Swipe Right to See the next card, Tap to see details and Click start work*

**Comment by john-brunelle** [comment]
@PixelantDesign I think that maybe with the new additions we may not need this as its more intuitive now. Could still add this though if you think necessary

**Comment by PixelantDesign** [comment]
I'm good with the improvements you've made!
