### ISSUE TITLE
Change swipe right interaction 

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/ios#29]
Change swipe right to view details

Remove red color association to Swipe left action

Add Start Work button on the details view.

**Comment by john-brunelle** [comment]
@PixelantDesign  

"Remove action associated to swipe left ( make it the same as clicking next." 
Not sure what action you are referring too. pls elaborate

When swiping right, do you still want the green color to show in the background?

**Comment by PixelantDesign** [comment]
Hi John- I removed that request. 

Could you remove the X at the bottom?

Thanks!

**Comment by PixelantDesign** [comment]
No green color on swipe right. Thanks!

**Comment by john-brunelle** [comment]
adding in 5747e00f4b3d9fe08bb85b75dbcb6d09307e7525

**Comment by PixelantDesign** [comment]
Looks good. Closing
