### ISSUE TITLE
get it live on the app store

### ISSUE THREAD

**Issue by owocki** [gitcoinco/ios#31]
what

*  on the profile page with the tabs, make the lists `account | bounties saved | bounties started` instead of `account | bounties claimed`
* add a bounty to the 'saved' list if its been swiped right
* add it to the started list if it's been started (this already works)

**Comment by john-brunelle** [comment]
k I can add back in the swipe right, however, we will need some API to save the bounty as well as to remove the saved bounty. @owocki can you add that into the API? Or if there is something there already pls let em know.

**Comment by john-brunelle** [comment]
I would also imagine that the saved bounty would need a 'start work' and 'remove' button in the details

**Comment by owocki** [comment]
> k I can add back in the swipe right, however, we will need some API to save the bounty as well as to remove the saved bounty. @owocki can you add that into the API? Or is there something there already pls let em know.

for simplicity, can we please just save the IDs locally instead of storing them server side?

**Comment by john-brunelle** [comment]
Could do that, I'll need a local database, implement the mapping (id, title, desc.) and crud. Not super quick thing but I can do. There might be some edges to work out but not sure about that yet.

**Comment by john-brunelle** [comment]
one thing to keep in mind is that if the user deletes the app, they will lose the saved

**Comment by owocki** [comment]
> Could do that, I'll need a local database, implement the mapping (id, title, desc.) and crud. Not super quick thing but I can do. There might be some edges to work out but not sure about that yet.

i was under the impression that there'd be some sort of drop in persistence we could use (whether its a full fledged DB or not i cannot say -- to me it seems like we're just storing an array of `int`s storing the IDs and then passing that to the API to get the actual metadata (title, desc)).  i guess that's not the case?  

> one thing to keep in mind is that if the user deletes the app, they will lose the saved

i think thats fine for now

**Comment by john-brunelle** [comment]
Hmmm, curious can the API handle a list of ids and return the associated bounties? Might be easier to serialize the data to the device myself, although the Realm DB is fairly easy to set up.

**Comment by owocki** [comment]
@john-brunelle yes!  use the `?standard_bounties_id__in=<list>` GET param
